name: 01-Building Blocks
on: 
  workflow_dispatch:
jobs:
  echo-hello:
    # if: github.branch.name == 'feature-latest'
    runs-on: ubuntu-latest
    steps:      
      - name: Say Hello
        run: echo "Hello, World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:      
      - name: Success step
        run: |
          echo "::debug::Set variable myVariable to true"
          echo "I will Succeed"
          exit 0
      - name: Say Goodbye
        run: echo "Goodbye!"
